[package]
name = "aart"
version = "0.1.0"
authors = ["Chuang Yu <cyu9960@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.2"
rusttype = "0.7.7"
clap = "2.33.0"